#!/usr/bin/env sh
# YandexWeatherCli installer.
# Скачивает релизный архив, раскладывает в каталог установки и генерирует wrapper.
set -eu

INVOKE_DIR=$(pwd)

REPO="${YWEATHER_REPO:-weavedwires/YandexWeatherCli}"
INSTALL_DIR="${YWEATHER_INSTALL_DIR:-$HOME/.local/share/yweather}"
BIN_DIR="${YWEATHER_BIN_DIR:-$HOME/.local/bin}"
VERSION=""
FORCE=0

usage() {
    echo "Использование: install.sh [--version X.Y.Z] [--force]" >&2
    echo "  --version X.Y.Z  установить конкретную версию (по умолчанию — последняя)" >&2
    echo "  --force          перезаписать places.json, если он уже есть" >&2
    echo "Окружение: YWEATHER_REPO, YWEATHER_INSTALL_DIR, YWEATHER_BIN_DIR" >&2
}

while [ "$#" -gt 0 ]; do
    case "$1" in
        --version)
            [ "$#" -ge 2 ] || { usage; exit 1; }
            VERSION="$2"
            shift 2
            ;;
        --force)
            FORCE=1
            shift
            ;;
        -h|--help)
            usage
            exit 0
            ;;
        *)
            echo "install.sh: неизвестный аргумент: $1" >&2
            usage
            exit 1
            ;;
    esac
done

# Проверка зависимостей
command -v java >/dev/null 2>&1 || { echo "install.sh: требуется Java 17+ (java)." >&2; exit 1; }
command -v unzip >/dev/null 2>&1 || { echo "install.sh: требуется unzip." >&2; exit 1; }
if command -v curl >/dev/null 2>&1; then
    FETCH="curl -fsSL"
elif command -v wget >/dev/null 2>&1; then
    FETCH="wget -qO-"
else
    echo "install.sh: требуется curl или wget." >&2
    exit 1
fi

# Определяем URL архива
if [ -n "$VERSION" ]; then
    case "$VERSION" in
        *v*) VERSION="${VERSION#v}" ;;
    esac
    URL="https://github.com/$REPO/releases/download/v$VERSION/yweather-$VERSION.zip"
else
    if [ "$FETCH" = "curl -fsSL" ]; then
        API_JSON=$(curl -fsSL "https://api.github.com/repos/$REPO/releases/latest")
    else
        API_JSON=$(wget -qO- "https://api.github.com/repos/$REPO/releases/latest")
    fi
    URL=$(printf '%s\n' "$API_JSON" \
        | sed -n 's/.*"browser_download_url": *"\([^"]*yweather-[^"]*\.zip\)".*/\1/p' \
        | head -n1)
    if [ -z "$URL" ]; then
        echo "install.sh: не удалось определить последний релиз репозитория $REPO." >&2
        exit 1
    fi
fi

TMP_DIR=$(mktemp -d)
trap 'rm -rf "$TMP_DIR"' EXIT

echo "Скачиваю $URL"
ARCHIVE="$TMP_DIR/yweather.zip"
if [ "$FETCH" = "curl -fsSL" ]; then
    curl -fsSL -o "$ARCHIVE" "$URL"
else
    wget -q -O "$ARCHIVE" "$URL"
fi

unzip -q "$ARCHIVE" -d "$TMP_DIR/pkg"

JAR=$(find "$TMP_DIR/pkg" -maxdepth 1 \( -name 'yweather.jar' -o -name 'yweather-*.jar' \) | head -n1)
if [ -z "$JAR" ]; then
    echo "install.sh: в архиве не найден yweather.jar." >&2
    exit 1
fi

mkdir -p "$INSTALL_DIR" "$BIN_DIR"

cp "$JAR" "$INSTALL_DIR/yweather.jar"

# api-key.txt.example — обновляем всегда; api-key.txt не трогаем, только создаём из примера.
cp "$TMP_DIR/pkg/api-key.txt.example" "$INSTALL_DIR/" 2>/dev/null || true
if [ ! -f "$INSTALL_DIR/api-key.txt" ] && [ -f "$INSTALL_DIR/api-key.txt.example" ]; then
    cp "$INSTALL_DIR/api-key.txt.example" "$INSTALL_DIR/api-key.txt"
    echo "Создан $INSTALL_DIR/api-key.txt из примера — вставь туда свой ключ."
fi

# places.json не перезаписываем, если уже есть (сохраняем любимые места).
if [ -f "$TMP_DIR/pkg/places.json" ]; then
    if [ ! -f "$INSTALL_DIR/places.json" ] || [ "$FORCE" -eq 1 ]; then
        cp "$TMP_DIR/pkg/places.json" "$INSTALL_DIR/places.json"
    else
        echo "places.json уже есть — оставляю как есть (для перезаписи: --force)."
    fi
fi

# SKILL.md копируем туда, откуда запущен установщик.
if [ -f "$TMP_DIR/pkg/SKILL.md" ]; then
    if [ "$INVOKE_DIR" = "$INSTALL_DIR" ]; then
        SKILL_TARGET="$INSTALL_DIR/SKILL.md"
    else
        SKILL_TARGET="$INVOKE_DIR/SKILL.md"
    fi
    cp "$TMP_DIR/pkg/SKILL.md" "$SKILL_TARGET"
    SKILL_COPIED="$SKILL_TARGET"
else
    SKILL_COPIED=""
fi

# Генерируем wrapper с зашитым путём к каталогу установки.
WRAPPER="$BIN_DIR/yweather"
cat > "$WRAPPER" <<EOF
#!/usr/bin/env sh
# Generated by install.sh — не редактируй вручную.
set -e
cd "$INSTALL_DIR"
exec java -jar "$INSTALL_DIR/yweather.jar" "\$@"
EOF
chmod 755 "$WRAPPER"

echo "Установлено:"
echo "  wrapper: $WRAPPER"
echo "  каталог: $INSTALL_DIR"
if [ -n "$SKILL_COPIED" ]; then
    echo "  SKILL.md: $SKILL_COPIED"
    echo "Передай $SKILL_COPIED используемому агенту, чтобы он знал, как вызывать yweather."
fi

case ":$PATH:" in
    *":$BIN_DIR:"*) ;;
    *)
        echo "Добавь каталог в PATH: export PATH=\"$BIN_DIR:\$PATH\"" >&2
        ;;
esac
